theme: jekyll-theme-minimal
title: Welcome to the homepage of Libby R.W. Ives.
description: Stay tuned for info on research and blog posts!
github: lrwives
twitter: glaciogeoLives
timezone: America/Detroit
